import React, { useEffect, useRef, useState } from "react";
import { Alert, Text, View } from "react-native";
import { Review } from "@astrokraft/db";
import { useSupabase } from "@/lib/supabase";
import { usePullToRefresh } from "@/hooks/use-pull-to-refresh";
import {
  Button,
  Card,
  EmptyState,
  FilterPills,
  LoadingState,
  RefreshableScrollView,
  Screen,
  ScreenHeader,
  StatusBadge
} from "@/components/ui";
import type { BadgeTone, ButtonVariant } from "@/components/ui";

const REVIEW_FILTERS = ["all", "pending", "approved", "rejected"] as const;
type ReviewFilter = (typeof REVIEW_FILTERS)[number];

const STATUS_TONE: Record<Review["status"], BadgeTone> = {
  pending: "saffron",
  approved: "success",
  rejected: "danger"
};

interface ReviewWithJoins extends Review {
  products: { title: string } | null;
  profiles: { full_name: string | null } | null;
}

interface ReviewAction {
  label: string;
  next: Review["status"];
  variant: ButtonVariant;
  confirmMessage?: string;
}

const STATUS_ACTIONS: Partial<Record<Review["status"], ReviewAction[]>> = {
  pending: [
    { label: "Approve", next: "approved", variant: "success" },
    { label: "Reject", next: "rejected", variant: "destructive", confirmMessage: "Reject this review?" }
  ],
  approved: [{ label: "Reject", next: "rejected", variant: "destructive", confirmMessage: "Reject this approved review?" }],
  rejected: [{ label: "Approve", next: "approved", variant: "success" }]
};

function formatDate(iso: string) {
  return new Date(iso).toLocaleDateString("en-IN", { day: "2-digit", month: "short", year: "numeric" });
}

function Stars({ rating }: { rating: number }) {
  return (
    <Text className="text-sm text-gold">
      {"★".repeat(rating)}
      <Text className="text-surface-border">{"★".repeat(5 - rating)}</Text>
    </Text>
  );
}

export default function ReviewsScreen() {
  const supabase = useSupabase();
  const [reviews, setReviews] = useState<ReviewWithJoins[]>([]);
  const [loading, setLoading] = useState(true);
  const [filter, setFilter] = useState<ReviewFilter>("pending");
  const [actionLoading, setActionLoading] = useState<string | null>(null);
  const [loadError, setLoadError] = useState<string | null>(null);
  // actionLoading tracks by review id alone (not id+status) so BOTH actions
  // for a review (e.g. Approve and Reject) disable together while either is
  // in flight — otherwise an admin could tap Approve then Reject before the
  // first write lands, firing two concurrent updates on the same row where
  // whichever request happens to finish last silently wins.
  const transitioningReviewIds = useRef(new Set<string>());
  // requestId is generated by the caller (fetchReviews/onRefresh/
  // runTransition), not inside loadReviews — so a superseded caller can
  // recognize its OWN result as stale even when the query throws, and skip
  // touching `loading`/`loadError` too, not just `reviews`. Checking
  // staleness only around setReviews (as a first pass did) still let a
  // stale request's *error* propagate to the newer request's caller, and
  // still let a stale request's `finally` clear the spinner while a newer
  // request was still in flight.
  const requestIdRef = useRef(0);

  const loadReviews = async (requestId: number) => {
    let query = supabase
      .from("reviews")
      .select("*, products(title), profiles(full_name)")
      .order("created_at", { ascending: false });
    if (filter !== "all") {
      query = query.eq("status", filter);
    }

    const { data, error } = await query;
    if (requestId !== requestIdRef.current) return;
    if (error) throw error;
    setReviews((data as ReviewWithJoins[]) || []);
  };

  const fetchReviews = async () => {
    const requestId = ++requestIdRef.current;
    setLoading(true);
    setLoadError(null);
    try {
      await loadReviews(requestId);
    } catch (err) {
      if (requestId !== requestIdRef.current) return;
      console.error("Error fetching reviews:", err);
      setLoadError("Could not load reviews. Pull to refresh.");
    } finally {
      if (requestId === requestIdRef.current) {
        setLoading(false);
      }
    }
  };

  useEffect(() => {
    fetchReviews();
  }, [filter]);

  const { refreshing, onRefresh } = usePullToRefresh(async () => {
    const requestId = ++requestIdRef.current;
    try {
      await loadReviews(requestId);
      if (requestId === requestIdRef.current) setLoadError(null);
    } catch (err) {
      if (requestId !== requestIdRef.current) return;
      console.error("Error refreshing reviews:", err);
      setLoadError("Could not load reviews. Pull to refresh.");
    } finally {
      // A pull-to-refresh that starts while the initial fetchReviews is
      // still in flight becomes the newest request — fetchReviews' own
      // finally then defers to it instead of clearing loading itself (see
      // the requestIdRef comment above). Without this, loading would stay
      // true forever once that happens, even though reviews did update.
      if (requestId === requestIdRef.current) setLoading(false);
    }
  });

  const runTransition = async (review: ReviewWithJoins, nextStatus: Review["status"]) => {
    if (transitioningReviewIds.current.has(review.id)) return;
    transitioningReviewIds.current.add(review.id);
    setActionLoading(review.id);

    try {
      const { error } = await supabase.from("reviews").update({ status: nextStatus }).eq("id", review.id);
      if (error) throw error;
    } catch (err: any) {
      transitioningReviewIds.current.delete(review.id);
      setActionLoading(null);
      Alert.alert("Error", err.message || "Failed to update review status.");
      return;
    }

    // The update itself already succeeded — a failure past this point is a
    // reload problem, not an update problem, and must never surface as
    // "Failed to update" (the admin would otherwise retry an action that
    // already went through, or worse, second-guess a status that's correct
    // in the database but stale on screen).
    const requestId = ++requestIdRef.current;
    try {
      await loadReviews(requestId);
    } catch (err) {
      console.error("Error reloading reviews after status update:", err);
      setLoadError("Status updated, but the list couldn't refresh. Pull to refresh.");
    } finally {
      // Same requestIdRef contract as fetchReviews/onRefresh (see the ref's
      // own comment above): this reload only clears loading if it's still
      // the current owner — otherwise an even newer request (e.g. another
      // filter change while this reload was in flight) is the one that
      // should control the spinner, not this superseded one.
      if (requestId === requestIdRef.current) setLoading(false);
      transitioningReviewIds.current.delete(review.id);
      setActionLoading(null);
    }
  };

  const handleAction = (review: ReviewWithJoins, action: ReviewAction) => {
    const run = () => runTransition(review, action.next);
    if (action.confirmMessage) {
      Alert.alert("Confirm", action.confirmMessage, [
        { text: "Cancel", style: "cancel" },
        { text: "Confirm", style: "destructive", onPress: run }
      ]);
    } else {
      run();
    }
  };

  return (
    <Screen>
      <ScreenHeader title="Reviews" subtitle="Customer Review Moderation">
        <FilterPills options={REVIEW_FILTERS} value={filter} onChange={setFilter} scroll />
      </ScreenHeader>

      <RefreshableScrollView refreshing={refreshing} onRefresh={onRefresh} contentContainerStyle={{ padding: 16, gap: 14 }}>
        {loading ? (
          <LoadingState />
        ) : loadError && reviews.length === 0 ? (
          <EmptyState title="Load Failed" description={loadError} />
        ) : reviews.length === 0 ? (
          <EmptyState title="No Reviews Found" description="Customer reviews submitted on the website will appear here." />
        ) : (
          <>
            {loadError ? (
              <View className="rounded-xl border border-saffron bg-saffron/10 px-4 py-3">
                <Text className="text-xs font-rubik-medium text-saffron">{loadError}</Text>
              </View>
            ) : null}
            {reviews.map((item) => {
              const actions = STATUS_ACTIONS[item.status] ?? [];

              return (
                <Card key={item.id} className="gap-2">
                  <View className="flex-row justify-between items-center">
                    <Text className="text-sm font-rubik-bold text-foreground flex-1" numberOfLines={1}>
                      {item.products?.title || "Unknown Product"}
                    </Text>
                    <StatusBadge label={item.status.toUpperCase()} tone={STATUS_TONE[item.status]} />
                  </View>

                  <View className="border-t border-surface-border pt-2 gap-1">
                    <View className="flex-row items-center gap-2">
                      <Stars rating={item.rating} />
                      {item.is_verified_buyer ? (
                        <Text className="text-[10px] font-rubik-bold uppercase text-primary">Verified Buyer</Text>
                      ) : null}
                    </View>
                    <Text className="text-xs text-ink-body">{item.comment}</Text>
                    <Text className="text-xs text-ink-muted">
                      {item.profiles?.full_name || "Anonymous"} · {formatDate(item.created_at)}
                    </Text>
                  </View>

                  {actions.length > 0 ? (
                    <View className="pt-2 border-t border-surface-border gap-2">
                      {actions.map((action) => (
                        <Button
                          key={action.next}
                          label={action.label}
                          variant={action.variant}
                          loading={actionLoading === item.id}
                          onPress={() => handleAction(item, action)}
                        />
                      ))}
                    </View>
                  ) : null}
                </Card>
              );
            })}
          </>
        )}
      </RefreshableScrollView>
    </Screen>
  );
}
